import { notFound, redirect } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '../../../../../lib/supabase/server';
import EventActions from './event-actions';
import '../../../../globals.css';

type Props={params:Promise<{id:string}>};
export default async function EventsPage({params}:Props){const{id}=await params;const supabase=await createClient();if(!supabase)return <DemoEvents/>;const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/');const{data:membership}=await supabase.from('circuit_memberships').select('role').eq('circuit_id',id).eq('user_id',user.id).maybeSingle();if(!membership)redirect('/');const{data:circuit}=await supabase.from('circuits').select('id,name,code').eq('id',id).maybeSingle();if(!circuit)notFound();const{data:members}=await supabase.from('members').select('id,first_name,last_name').eq('circuit_id',id).eq('status','active').order('last_name');const{data:events}=await supabase.from('membership_events').select('id,event_type,event_date,member_id,details').in('member_id',(members||[]).map(m=>m.id)).order('event_date',{ascending:false}).limit(100);return <EventsView circuit={circuit} members={members||[]} events={events||[]}/>}
function DemoEvents(){return <EventsView circuit={{id:'demo',name:'Goromonzi Circuit',code:'GOR-001'}} members={[{id:'m1',first_name:'Tariro',last_name:'Moyo'}]} events={[{id:'e1',event_type:'confirmation',event_date:'2026-05-18',member_id:'m1',details:{notes:'Sunday service'}}]}/>}
function EventsView({circuit,members,events}:{circuit:{id:string;name:string;code?:string|null};members:Array<{id:string;first_name:string;last_name:string}>;events:Array<any>}){const memberName=(id:string)=>{const m=members.find(x=>x.id===id);return m?`${m.first_name} ${m.last_name}`:'Member record'};const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());return <main className="root-workspace"><header className="navbar"><Link className="wordmark" href={`/circuit/${circuit.id}/members`}><span className="mark"><i/></span><strong>Wesley<span>Link</span></strong></Link><div className="scope-pill">{circuit.name} · Membership events</div><div className="tools"><Link className="back-root" href={`/circuit/${circuit.id}/members`}>Register</Link><b>TM</b></div></header><section className="root-content"><div className="root-heading"><div><em>Historical movement</em><h1>Membership events.</h1><p>Record the changes that drive annual statistics and ZEAC reporting.</p></div><EventActions circuitId={circuit.id} members={members}/></div><div className="root-table"><div className="panel-head"><h2>Event history</h2><button className="panel-link">Export events</button></div>{events.length?events.map(event=><div className="root-table-row" key={event.id}><span className="row-mark blue"/><div><strong>{label(event.event_type)}</strong><small>{memberName(event.member_id)} · {event.details?.notes||'No note'}</small></div><b>{event.event_date}</b></div>):<div className="empty-state"><strong>No membership events recorded.</strong><p>Record the first baptism, transfer, confirmation or other movement.</p></div>}</div></section></main>}
