'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '../../../../lib/supabase/client';

type Church = { id: string; name: string; sections?: { id: string; name: string }[] };
export default function MemberActions({ circuitId, churches }: { circuitId: string; churches: Church[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(''); const form = new FormData(event.currentTarget); const supabase = createClient(); if (!supabase) { setError('Connect Supabase to add a live member.'); setSaving(false); return; } const { error: insertError } = await supabase.from('members').insert({ circuit_id: circuitId, church_id: String(form.get('church_id')), section_id: String(form.get('section_id') || '') || null, first_name: String(form.get('first_name')), last_name: String(form.get('last_name')), gender: String(form.get('gender')), category: String(form.get('category')) }); if (insertError) { setError(insertError.message); setSaving(false); return; } setOpen(false); setSaving(false); router.refresh(); }
  if (!open) return <button className="action" onClick={() => setOpen(true)}>＋ Add member</button>;
  return <form className="root-form member-form" onSubmit={submit}><div><label>First name<input name="first_name" placeholder="First name" required /></label><label>Last name<input name="last_name" placeholder="Last name" required /></label></div><div><label>Church<select name="church_id" required>{churches.map(church=><option key={church.id} value={church.id}>{church.name}</option>)}</select></label><label>Section<select name="section_id"><option value="">No section assigned</option>{churches.flatMap(church=>(church.sections||[]).map(section=><option key={section.id} value={section.id}>{section.name}</option>))}</select></label></div><div><label>Gender<select name="gender"><option value="female">Female</option><option value="male">Male</option></select></label><label>Category<select name="category"><option value="full_member">Full member</option><option value="adult_probationer">Adult probationer</option><option value="child_under_12">Child under 12</option><option value="affiliate">Affiliate</option><option value="associate">Associate</option></select></label></div>{error && <div className="auth-error">{error}</div>}<div className="root-form-actions"><button type="button" className="cancel" onClick={() => setOpen(false)}>Cancel</button><button className="action" disabled={saving}>{saving ? 'Saving…' : 'Save member →'}</button></div></form>;
}
